/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author julio
 */
public class TelasAtv03 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelasAtv03.class.getName());

    /**
     * Creates new form TelasAtv03
     */
    public TelasAtv03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldDobroTriplo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonCalcDobroTriplo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaidaDobroTriplo = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldLargura = new javax.swing.JTextField();
        jTextFieldAltura = new javax.swing.JTextField();
        jButtonCalcAreaRetangulo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSaidaAreaRetangulo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelTempCelsius = new javax.swing.JLabel();
        jButtonCalcFahrenheit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaSaidaFah = new javax.swing.JTextArea();
        jTextFieldTempCelsius = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelPrecoProd = new javax.swing.JLabel();
        jTextFieldPrecoProd = new javax.swing.JTextField();
        jButtonCalcDesc = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaSaidaPrecDesc = new javax.swing.JTextArea();
        jLabelPrecoProd1 = new javax.swing.JLabel();
        jTextFieldDescProduto = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabelIdade = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaSaidaIdade = new javax.swing.JTextArea();
        jTextFieldIdade = new javax.swing.JTextField();
        jButtonCalcIdade = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabelPrecoProd2 = new javax.swing.JLabel();
        jTextFieldNum1 = new javax.swing.JTextField();
        jLabelPrecoProd3 = new javax.swing.JLabel();
        jTextFieldNum2 = new javax.swing.JTextField();
        jButtonMaiorMenor = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaSaidaMaior = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabelMedia = new javax.swing.JLabel();
        jTextFieldMedia = new javax.swing.JTextField();
        jButtonMedia = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaSaidaMedia = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldDobroTriplo.addActionListener(this::jTextFieldDobroTriploActionPerformed);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Digite um número");

        jButtonCalcDobroTriplo.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButtonCalcDobroTriplo.setText("Mostrar Dobro e Triplo");
        jButtonCalcDobroTriplo.addActionListener(this::jButtonCalcDobroTriploActionPerformed);

        jTextAreaSaidaDobroTriplo.setColumns(20);
        jTextAreaSaidaDobroTriplo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaidaDobroTriplo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDobroTriplo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(347, 347, 347))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonCalcDobroTriplo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 208, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDobroTriplo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCalcDobroTriplo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dobro e triplo", jPanel1);

        jTextFieldLargura.addActionListener(this::jTextFieldLarguraActionPerformed);

        jButtonCalcAreaRetangulo.setText("Calcular");
        jButtonCalcAreaRetangulo.addActionListener(this::jButtonCalcAreaRetanguloActionPerformed);

        jTextAreaSaidaAreaRetangulo.setColumns(20);
        jTextAreaSaidaAreaRetangulo.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSaidaAreaRetangulo);

        jLabel2.setText("Largura");

        jLabel3.setText("Altura");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldAltura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jButtonCalcAreaRetangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldLargura)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonCalcAreaRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Área retâng", jPanel2);

        jLabelTempCelsius.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelTempCelsius.setText("Temperatura Celsius");

        jButtonCalcFahrenheit.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonCalcFahrenheit.setText("Calcular em Fahrenheit");
        jButtonCalcFahrenheit.addActionListener(this::jButtonCalcFahrenheitActionPerformed);

        jTextAreaSaidaFah.setColumns(20);
        jTextAreaSaidaFah.setRows(5);
        jScrollPane3.setViewportView(jTextAreaSaidaFah);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTempCelsius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldTempCelsius)
                    .addComponent(jButtonCalcFahrenheit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabelTempCelsius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTempCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCalcFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conv de temp", jPanel3);

        jLabelPrecoProd.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelPrecoProd.setText("Preço do Produto");

        jButtonCalcDesc.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonCalcDesc.setText("Calcular");
        jButtonCalcDesc.addActionListener(this::jButtonCalcDescActionPerformed);

        jTextAreaSaidaPrecDesc.setColumns(20);
        jTextAreaSaidaPrecDesc.setRows(5);
        jScrollPane4.setViewportView(jTextAreaSaidaPrecDesc);

        jLabelPrecoProd1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelPrecoProd1.setText("Desconto Aplicado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelPrecoProd1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDescProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrecoProd)
                    .addComponent(jLabelPrecoProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCalcDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelPrecoProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPrecoProd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButtonCalcDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Preço com desc", jPanel4);

        jLabelIdade.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelIdade.setText("Idade");

        jTextAreaSaidaIdade.setColumns(20);
        jTextAreaSaidaIdade.setRows(5);
        jScrollPane5.setViewportView(jTextAreaSaidaIdade);

        jButtonCalcIdade.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonCalcIdade.setText("Meses de Vida");
        jButtonCalcIdade.addActionListener(this::jButtonCalcIdadeActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldIdade)
                    .addComponent(jButtonCalcIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabelIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCalcIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Idade em meses", jPanel5);

        jLabelPrecoProd2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelPrecoProd2.setText("Número 1");

        jLabelPrecoProd3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelPrecoProd3.setText("Número 2");

        jButtonMaiorMenor.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonMaiorMenor.setText("Calcular");
        jButtonMaiorMenor.addActionListener(this::jButtonMaiorMenorActionPerformed);

        jTextAreaSaidaMaior.setColumns(20);
        jTextAreaSaidaMaior.setRows(5);
        jScrollPane6.setViewportView(jTextAreaSaidaMaior);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelPrecoProd3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNum2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jTextFieldNum1)
                    .addComponent(jLabelPrecoProd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMaiorMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelPrecoProd2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPrecoProd3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButtonMaiorMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Verif maior núm", jPanel6);

        jLabelMedia.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelMedia.setText("Média do Aluno");

        jButtonMedia.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonMedia.setText("Calc Média");
        jButtonMedia.addActionListener(this::jButtonMediaActionPerformed);

        jTextAreaSaidaMedia.setColumns(20);
        jTextAreaSaidaMedia.setRows(5);
        jScrollPane7.setViewportView(jTextAreaSaidaMedia);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldMedia)
                    .addComponent(jButtonMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabelMedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aprov ou rep", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDobroTriploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDobroTriploActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDobroTriploActionPerformed

    private void jButtonCalcDobroTriploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcDobroTriploActionPerformed

        
        double n1 = Double.parseDouble(jTextFieldDobroTriplo.getText());
        
        double dobrar = n1 * 2;
        double triplicar = n1 * 3;
        
        jTextAreaSaidaDobroTriplo.setText("O número "+n1+" quando é dobrado fica "+dobrar+" \n e quando é triplicado se torna "+triplicar);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalcDobroTriploActionPerformed

    private void jTextFieldLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLarguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLarguraActionPerformed

    private void jButtonCalcAreaRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcAreaRetanguloActionPerformed

        
        double largura = Double.parseDouble(jTextFieldLargura.getText());
        double altura = Double.parseDouble(jTextFieldAltura.getText());
        
        double area = largura * altura;
                
        jTextAreaSaidaAreaRetangulo.setText("A área do retângulo é "+area);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalcAreaRetanguloActionPerformed

    private void jButtonCalcFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcFahrenheitActionPerformed
        
        double TempCelsius = Double.parseDouble(jTextFieldTempCelsius.getText());
        
        double CalcFahrenheit = (TempCelsius * 9/5) + 32;
        
        jTextAreaSaidaFah.setText(TempCelsius+" em Fahrenheit é "+CalcFahrenheit);
        
        
        

        
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalcFahrenheitActionPerformed

    private void jButtonCalcDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcDescActionPerformed

        double ValorProd = Double.parseDouble(jTextFieldPrecoProd.getText());
        double ValorDesc = Double.parseDouble(jTextFieldDescProduto.getText());
        
        double CalcDesc = (ValorProd * ValorDesc)/ 100;
        double ValFinal = ValorProd - CalcDesc;
        
        jTextAreaSaidaPrecDesc.setText("Com R$ "+ValorProd+" você terá R$ "+CalcDesc+ " de Desconto. \n O Valor final do Produto é: "+ValFinal);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalcDescActionPerformed

    private void jButtonCalcIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcIdadeActionPerformed

        int idade = Integer.parseInt(jTextFieldIdade.getText());
        
        int CalcIdadeMeses = idade * 12;
        
        jTextAreaSaidaIdade.setText("Você tem "+CalcIdadeMeses+" meses de vida");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalcIdadeActionPerformed

    private void jButtonMaiorMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaiorMenorActionPerformed

        double n1 = Double.parseDouble(jTextFieldNum1.getText());
        double n2 = Double.parseDouble(jTextFieldNum2.getText());
        
        String MaiorValor;
        
        if (n1 > n2){
        MaiorValor = "O maior valor é: " + n1;
        }else if (n1 < n2){
        MaiorValor = "O maior valor é: " + n2;
        }else{
        MaiorValor = "Dois valores iguais";
        }
        
        jTextAreaSaidaMaior.setText(MaiorValor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMaiorMenorActionPerformed

    private void jButtonMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMediaActionPerformed

        double media = Double.parseDouble(jTextFieldMedia.getText());
        
        String ResultadoFinal;
        
        if (media >= 7){
            ResultadoFinal = "Aprovado";
        }else{
            ResultadoFinal = "Reprovado";
        }
        
        jTextAreaSaidaMedia.setText(ResultadoFinal);
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelasAtv03().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcAreaRetangulo;
    private javax.swing.JButton jButtonCalcDesc;
    private javax.swing.JButton jButtonCalcDobroTriplo;
    private javax.swing.JButton jButtonCalcFahrenheit;
    private javax.swing.JButton jButtonCalcIdade;
    private javax.swing.JButton jButtonMaiorMenor;
    private javax.swing.JButton jButtonMedia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelMedia;
    private javax.swing.JLabel jLabelPrecoProd;
    private javax.swing.JLabel jLabelPrecoProd1;
    private javax.swing.JLabel jLabelPrecoProd2;
    private javax.swing.JLabel jLabelPrecoProd3;
    private javax.swing.JLabel jLabelTempCelsius;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaSaidaAreaRetangulo;
    private javax.swing.JTextArea jTextAreaSaidaDobroTriplo;
    private javax.swing.JTextArea jTextAreaSaidaFah;
    private javax.swing.JTextArea jTextAreaSaidaIdade;
    private javax.swing.JTextArea jTextAreaSaidaMaior;
    private javax.swing.JTextArea jTextAreaSaidaMedia;
    private javax.swing.JTextArea jTextAreaSaidaPrecDesc;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldDescProduto;
    private javax.swing.JTextField jTextFieldDobroTriplo;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldLargura;
    private javax.swing.JTextField jTextFieldMedia;
    private javax.swing.JTextField jTextFieldNum1;
    private javax.swing.JTextField jTextFieldNum2;
    private javax.swing.JTextField jTextFieldPrecoProd;
    private javax.swing.JTextField jTextFieldTempCelsius;
    // End of variables declaration//GEN-END:variables
}
